services:
  bank-card:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      JWT_LIFETIME: ${JWT_LIFETIME}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      LIFETIME_IN_YEARS: ${LIFETIME_IN_YEARS}
      CORS_URL: ${CORS_URL}
      CORS_PORT: ${CORS_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: