spring:
  application:
    name: bank.card
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/changelog.sql
cors:
  url: ${CORS_URL}
  port: ${CORS_PORT}
jwt:
  lifetime: ${JWT_LIFETIME}
  secret: ${JWT_SECRET_KEY}
bank-card:
  encryption-key: ${ENCRYPTION_KEY}
  lifetime-in-years: ${LIFETIME_IN_YEARS}