spring:
  application:
    name: bank.card
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/changelog.sql
cors:
  url:
  port:
jwt:
  lifetime:
  secret:
bank-card:
  encryption-key:
  lifetime-in-years: