--liquibase formatted sql

--changeset v7nny:CREATE_TABLE_Users
CREATE TABLE IF NOT EXISTS Users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE CHECK(LENGTH(TRIM(username)) >= 5),
    email VARCHAR NOT NULL UNIQUE CHECK(LENGTH(TRIM(email)) > 0),
    password VARCHAR NOT NULL
);

--changeset v7nny:CREATE_TABLE_Roles
CREATE TABLE IF NOT EXISTS Roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);

--changeset v7nny:CREATE_TABLE_Users_roles
CREATE TABLE IF NOT EXISTS Users_roles (
    user_id INT REFERENCES Users(id) NOT NULL,
    role_id INT REFERENCES Roles(id) NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

--changeset v7nny:CREATE_TABLE_Bank_cards
CREATE TABLE IF NOT EXISTS Bank_cards (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encrypted_card_number VARCHAR(64) NOT NULL UNIQUE,
    masked_card_number VARCHAR(19) NOT NULL,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(7) NOT NULL DEFAULT 'ACTIVE' CHECK(
        status IN ('ACTIVE', 'BLOCKED', 'EXPIRED')),
    expiry_date DATE NOT NULL,
    user_id INT REFERENCES Users(id) NOT NULL
);

--changeset v7nny:CREATE_TABLE_Block_card_requests
CREATE TABLE IF NOT EXISTS Block_card_requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(11) NOT NULL DEFAULT 'PENDING' CHECK(
        status IN ('PENDING', 'COMPLETED')),
    bank_card_id INT REFERENCES Bank_cards(id) NOT NULL,
    user_id INT REFERENCES Users(id) NOT NULL
);

--changeset v7nny:INSERT_INTO_Roles
INSERT INTO Roles(name) VALUES('ROLE_USER'), ('ROLE_ADMIN');